on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --target x86_64-unknown-linux-musl --release
        env:
          IHN_SBATCH_JOB_ARRAY_VERSION: ${{ github.ref_name }}
      - name: create GitHub release
        run: gh release create ${{ github.ref_name }} target/x86_64-unknown-linux-musl/release/ihn-sbatch-job-array
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZIP_FILE: ihn-sbatch-job-array-${{ github.ref_name }}.zip
